inherit_from: configs/tartanair/tartanair.yaml
grid_len: #对于office0
  coarse: 2 # 2
  middle: 0.32 # 0.32
  fine: 0.16 #0.16
  color: 0.16
  bound_divisible: 0.32
tracking:
  gt_camera: False #? True False
 #? True False
meshing: #这些参数要调整
  level_set: 0
  resolution: 256 # 256 change to 512 for higher resolution geometry
  eval_rec: True #默认只对replica True False 测试打开
  clean_mesh: True # True False no clean
  depth_test: False
  mesh_coarse_level: False
  clean_mesh_bound_scale: 1.02
  get_largest_components: False
  color_mesh_extraction_method: direct_point_query
  remove_small_geometry_threshold: 0.2 # 0.2 0.4 增大阈值 想清理更多
mapping: #更改
  # # office1 no norm raw [[-25.5,12.1],[-3.9,2.5],[-15.1,15.1]] dtrunc20
  bound: [[-25.5,15.7],[-3.9,2.5],[-15.1,15.1]]
  marching_cubes_bound: [[-25.5,12.1],[-1.8,2.5],[-15.1,15.1]] # -2.0 想不显示roof -1.8
  # 1.4m
  every_frame: 5
  vis_freq: 5 # 一般是every_frame的整数倍
  vis_inside_freq: 29 # 30 29
  mesh_freq: 50
  ckpt_freq: 400 # 500 200 600
  keyframe_every: 50 #和关键帧密度有关50  20 30 
  save_selected_keyframes_info: True # True
  mapping_window_size: 10 # 5 10
  pixels: 5000 #这是kfs总的像素数吧 
  iters_first: 1500
  iters: 60 # 测试增大迭代次数 60 120 600 1000
  # gtw nerf bound [[-26, 1],[-1,1],[-7.,11]]
  BA: True # True #mapping是否一同优化位姿 False
  # no_vis_on_first_frame: False # False True
  # color_refine: False # True False global color 优化的处理 默认开 测试关闭
data:
  input_folder: Datasets/TartanAir/office/Easy/P001 #Datasets/tcsvt/whole-floor/W2/glass
  output: output/tartanair/office/P001 # nope nonormnerf2
cam:  #NOTE: intrinsic is different per scene in TUM e.g: Scene01
  H: 480 # 480 375
  W: 640 # 640 1242
  fx: 320.0
  fy: 320.0
  cx: 320.0 #318.6
  cy: 240.0 #255.3
  png_depth_scale: 1. #设置 https://github.com/castacks/tartanair_tools/blob/master/data_type.md
  # crop_edge: 0 #8
  # crop_size: [384,512]
  # distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
  depth_trunc: -1 # add for limit bound discard larger depth 20.0
  sky_depth: 10000