inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-2.0,11.0],[-2.0,11.5],[-2.0,5.5]] #[[-2.0,11.0],[-2.0,11.5],[-2.0,5.5]]
  marching_cubes_bound: [[-2.0,8.0],[0.0,8.5],[-2.0,5.5]]
data:
  input_folder: Datasets/scannet/scans/scene0001_01
  output: output/scannet/scans/scene0001_01mb1
# gtw nerf bound [[2.1, 3.7],[4.0,7.0],[1.3,1.6]]

