inherit_from: configs/ScanNet/scannet.yaml
mapping:
  # bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
  # marching_cubes_bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
  # my pcd nerf frame
  # [[-2.5,7.0],[-9.4,1.1],[-2.7,0.0]]
  # no final transform 就是原坐标系的点云的bound..
  # [[-2.5,7.0],[-1.1,9.4],[-0.0,2.7]]
  # traj bound
  # [[2.2,4.8],[2.8,5.7],[1.3,1.8]]

  # bound: [[-4.2,3.4],[-3.1,3.4],[-5.0,3.5]]
  # marching_cubes_bound: [[-4.2,3.4],[-3.1,3.4],[-5.0,3.5]]
  bound: [[-4.2,3.4],[-3.4,3.1],[-3.5,5.0]]
  marching_cubes_bound: [[-4.2,3.4],[-3.4,3.1],[-3.5,5.0]]

  # normalize first
  # traj bound
  # [[-0.7,2.1],[-1.1,0.5],[-0.8,1.9]]
  # my pcd nerf frame
  # [[-4.2,3.4],[-3.1,3.4],[-5.0,3.5]]
  # no final transform 就是原坐标系的点云的bound..
  # [[-4.2,3.4],[-3.4,3.1],[-3.5,5.0]]

data:
  input_folder: Datasets/scannet/scans/scene0059_00
  output: output/scannet/scans/scene0059_00my1