# 只是用来生成 三角剖分的粗糙深度图
inherit_from: configs/TUM_RGBD/tum.yaml
use_prior: False # 是否载入作为先验的 pose 和depth
mapping:
  bound: [[-4.7,4.3],[-5.9,1.5],[-2.5, 10.3]]
  marching_cubes_bound: [[-5.0,13.4],[-5.0,13.7],[-5.0,5.0]]
data:
  input_folder: Datasets/TUM_RGBD/rgbd_dataset_freiburg2_xyz
  output: output/TUM_RGBD/rgbd_dataset_freiburg2_xyz-dt
  prior_folder: /home/dlr/Project1/ORB_SLAM2_Enhanced/result/tum/fr2xyz #暂时
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 520.9
  fy: 521.0
  cx: 325.1
  cy: 249.7
  # crop_edge: 8 # 先都用全图 得到深度先验
  # crop_size: [384,512]
  distortion: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
