dataset: 'tumrgbd'
prior_scale: 1 # 用于prior 的pose 和 depth map 的尺度和 Gt 的对齐因子 这里default 1
use_prior: True # 是否载入作为先验的 pose 和depth
coarse: False # False True
rgbonly: True # 增加选项 是否为单目模式 即无depth loss
guidesample: True # 增加选项 测试深度引导对在线的作用 False 默认 
grid_len: #对于outdoor该如何设
  coarse: 2 
  middle: 0.16
  fine: 0.08
  color: 0.08
  bound_divisible: 0.32
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: True #? 分开优化旋转 平移 好像
  const_speed_assumption: True
  gt_camera: False #?
  lr: 0.01     
  pixels: 5000
  iters: 200
mapping:
  every_frame: 5 #? mapping的频率 改为5
  vis_freq: 50
  vis_inside_freq: 25
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 5000 #被用来优化的图像上的像素数吧
  iters_first: 1500
  iters: 60
  no_vis_on_first_frame: False # True
  # no_mesh_on_first_frame: False
  no_log_on_first_frame: False
  middle_iter_ratio: -1. # 0.4 # rgbonly时 只有color stage
  fine_iter_ratio: -1. # 0.6
  save_selected_keyframes_info: True
  frustum_feature_selection: False
  keyframe_selection_method: 'global' # 'overlap'当wo gt depth就不能用 prior 即使用来自orb的2d-3d对应关系来寻找共视kf 
  color_loss_mask: False # color loss 是否用depth mask
  use_regulation: False # 对于nice 是否对深度前的区域正则化 sigma /occ
  use_sparse_loss: True # 稀疏点 单独构建 depth color loss
  use_sparse_color: True # 上面就特指sparse depth 这里kpt上的 color 就在吧
  w_color_loss: 1.
  w_depth_loss: 0.3 # 跟depth loss 加权
rendering:
  N_samples: 32 #N_strat
  N_surface: 32 #在深度周围 16| 0 
  N_importance: 32 #为啥是0 nerf里是有这一步 hirecial 采样吧 12(imap*) 16(总数和原始保持一致) 32
  lindisp: False
  perturb: 0.0 
  less_sample_space: True # 是否用粗糙深度来在surface附近区间内多重采样
  up_sample_steps: 2 # 在表面附件多重采样的次数 暂时每次16个
  emperical_range: 0.15 # 增加参数控制 surface 的range 比例 0.05| 0.1 0.15
  use_KL_loss: True # 是否使用ds-nerf的sigma loss True
  # https://github.com/dunbar12138/DSNeRF/blob/d9deb70ac1464348aebbe5e32fc98aeca1920f70/run_nerf.py#L527
  raw_noise_std: 1.0 # 'std dev of noise added to regularize sigma_a output, 1e0 recommended' 只是对于nerf nice-slam还用不上
  sigma_lambda: 0.01 # 权重因子 used for KL loss 0.1 

cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0 #设置
  crop_edge: 0