inherit_from: configs/Replica/replica.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  marching_cubes_bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  BA: False
  no_vis_on_first_frame: False # True
  # every_frame: 25 # 5| 25
data:
  input_folder: Datasets/Replica/office2
  output: output_bl/Replica/office2gtp-rgb-resize2
cam:
  # depth_trunc: -1 # add for limit bound discard larger depth
  crop_size: [340,600] # 使用一半大小的图片