inherit_from: configs/Replica/replica.yaml
# scale: 5 # 深度和pose 平移都x此尺度1 4 5 测试
# coarse: False #是否优化coarse level geometry 地图 True  debug 时就先关掉该线程 False
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  marching_cubes_bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  BA: False # True #mapping是否一同优化位姿 False
  iters_first: 4000 # 1500| 2000 4000
  iters: 4000 # 测试增大迭代次数 60| 100 120 600 1000
  vis_freq: 50 # 每# 帧 打印并可视化 mapping的中间结果
  vis_inside_freq: 200 # 30| 200 20 某次mapping 每#次迭代看下log和中间结果
  # no_vis_on_first_frame: False # True
  mapping_window_size: 5
  pixels: 1000 # 窗口内若干关键帧使用的总像素(ray)数 实际中每个kf中ray数目更少 1000/5=200| 2048 4096
  depth_tvnorm_maxstep: 1600000 # Max step for depth tv norm decay. regnerf 里step是总迭代次数 我这里decay策略 得改大一些 512 | 2048   25440=399*60+1500
data:
  input_folder: Datasets/Replica/office0
  # 新建文件夹保存 regnerf 的实验 都是默认没有depth loss
  output: output-reg/Replica/office0gt-nodloss-p1k-f4k-it4k # -pix1k-f1500-it60 没提 表示按照默认参数
cam:
  # depth_trunc: -1 # add for limit bound discard larger depth
  # 增加根据dnet预测的深度的不确定性来prune pred depth
  dstdv_cut_max: -1  # 对于office 实际最大值在0.35左右 0.25 0.2 0.15