inherit_from: configs/Replica/replica.yaml
# scale: 5 # 深度和pose 平移都x此尺度1 4 5 测试
# coarse: False #是否优化coarse level geometry 地图 True  debug 时就先关掉该线程 False
rgbonly: True # 增加选项 是否为单目模式 即无depth loss
tracking:
  gt_camera: True #? True False
  vis_freq: 2
mapping:
  no_vis_on_first_frame: False # True
  # no_mesh_on_first_frame: False
  no_log_on_first_frame: False
  bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  marching_cubes_bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  BA: False # True #mapping是否一同优化位姿 False
  iters_first: 4000 # 1500| 2000 4000
  iters: 4000 # 测试增大迭代次数 60| 100 120 600 1000
  vis_freq: 5 # 每# 帧 打印并可视化 mapping的中间结果
  vis_inside_freq: 200 # 30| 200 20 某次mapping 每#次迭代看下log和中间结果
  no_vis_on_first_frame: False # True
  mapping_window_size: 5
  every_frame: 5 # 5| 25 和 离线的80kf来对比
  keyframe_every: 50
  pixels: 1000 # 窗口内若干关键帧使用的总像素(ray)数 实际中每个kf中ray数目更少 1000/5=200| 2048 4096
  anneal_nearfar: True # Whether to anneal near/far planes. 暂时不开
  anneal_nearfar_steps: 500 # Steps for near/far annealing. 512 | 1000 500 100 50 
  anneal_nearfar_perc: 0.1 # Percentage for near/far annealing. 0.0001| 0.001
  anneal_mid_perc: 1.0 # Perc for near/far mid point. 1.0 | 0.5
  fix_fine: False # 测试几何decoder也一同优化
  fix_color: False
  mesh_freq: 5
rendering:
  N_samples: 32 #N_strat
  N_surface: 0 #在深度周围 16| 0 
  N_importance: 32 #为啥是0 nerf里是有这一步 hirecial 采样吧 12(imap*) 16(总数和原始保持一致) 32
  lindisp: False
  perturb: 0.0 
data:
  input_folder: Datasets/Replica/office0
  # 新建文件夹保存 regnerf 的实验 都是默认没有depth loss
  output: output-reg/Replica/office0gt-nodloss2-init-anneal3-f4k-it4k-optgeomlp # -pix1k-f1500-it60 没提 表示按照默认参数
  endnum: 16 # 实际那前#帧 若为-1 则默认全部
cam:
  # depth_trunc: -1 # add for limit bound discard larger depth
  # 增加根据dnet预测的深度的不确定性来prune pred depth
  dstdv_cut_max: -1  # 对于office 实际最大值在0.35左右 0.25 0.2 0.15