inherit_from: configs/Replica/replica_imap.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  marching_cubes_bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  BA: False # True #mapping是否一同优化位姿 False
data:
  input_folder: Datasets/Replica/office0
  output: output_imap_bl/Replica/office0gtp-rgb
# cam:
  # crop_size: [340,600] # 使用一半大小的图片