inherit_from: configs/Replica/replica_imap.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
  marching_cubes_bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
  BA: False # True #mapping是否一同优化位姿 False
data:
  input_folder: Datasets/Replica/office1
  output: /mnt/lustre/donglongrui/nice-slam/output_imap_bl/Replica/office1gtp-rgb
# cam:
  # crop_size: [340,600] # 使用一半大小的图片