inherit_from: configs/Replica/replica.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-3.7,7.8],[-4.8,6.7],[-3.7,4.1]]
  marching_cubes_bound: [[-3.7,7.8],[-4.8,6.7],[-3.7,4.1]]
  BA: False
  no_vis_on_first_frame: False # True
  # every_frame: 25 # 5| 25
data:
  input_folder: Datasets/Replica/office4
  output: /mnt/lustre/donglongrui/nice-slam/output_bl/Replica/office4gtp-rgb-resize2
cam:
  # depth_trunc: -1 # add for limit bound discard larger depth
  crop_size: [340,600] # 使用一半大小的图片