inherit_from: configs/Replica/replica_imap.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  marching_cubes_bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  BA: False # True #mapping是否一同优化位姿 False
data:
  input_folder: Datasets/Replica/office3
  output: output_imap_bl/Replica/office3gtp-rgb
# cam:
  # crop_size: [340,600] # 使用一半大小的图片