dataset: 'replica'
rgbonly: True # 增加选项 是否为单目模式 即无depth loss
guidesample: False # 增加选项 测试深度引导对在线的作用 False 默认
meshing:
  eval_rec: True
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.0005
  pixels: 5000
  iters: 50
mapping:
  every_frame: 5
  vis_freq: 50 # 每50帧有可视化
  vis_inside_freq: 30 # 在上面条件下 迭代每30次 保存可视化结果
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 5000
  iters_first: 1500
  iters: 300
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0