dataset: 'replica'
scale: 1
prior_scale: 1 # 用于prior 的pose 和 depth map 的尺度和 Gt 的对齐因子 这里default 1
use_prior: True # 是否载入作为先验的 pose 和depth
coarse: False # False True
rgbonly: True # 增加选项 是否为单目模式 即无depth loss
guidesample: False # 增加选项 测试深度引导对在线的作用 False 默认 
verbose: True 
meshing:
  eval_rec: True
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 10
mapping:
  every_frame: 5
  vis_freq: 50
  vis_inside_freq: 30
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1500
  iters: 60
  middle_iter_ratio: -1. # 0.4 # rgbonly时 只有color stage
  fine_iter_ratio: -1. # 0.6
  save_selected_keyframes_info: True
  color_loss_mask: False # color loss 是否用depth mask
  use_regulation: False # 对于nice 是否对深度前的区域正则化 sigma /occ
  use_sparse_loss: False # 稀疏点 单独构建 depth color loss
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format uint16 10m内
  crop_edge: 0