inherit_from: configs/Replica/replica_imap.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  BA: False # True #mapping是否一同优化位姿 False
data:
  input_folder: Datasets/Replica/room0
  output: /mnt/lustre/donglongrui/nice-slam/output_imap_bl/Replica/room0gtp-rgb
# cam:
  # crop_size: [340,600] # 使用一半大小的图片