inherit_from: configs/Replica/replica.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  marching_cubes_bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  BA: False
  no_vis_on_first_frame: False # True
  # every_frame: 25 # 5| 25
data:
  input_folder: Datasets/Replica/room2
  output: /mnt/lustre/donglongrui/nice-slam/output_bl/Replica/room2gtp-rgb-resize2
cam:
  # depth_trunc: -1 # add for limit bound discard larger depth
  crop_size: [340,600] # 使用一半大小的图片