inherit_from: configs/Replica/replica_imap.yaml
tracking:
  gt_camera: True #? True False
mapping:
  bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  marching_cubes_bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  BA: False # True #mapping是否一同优化位姿 False
data:
  input_folder: Datasets/Replica/room2
  output: output_imap_bl/Replica/room2gtp-rgb
# cam:
  # crop_size: [340,600] # 使用一半大小的图片