dataset: 'tcsvt'
sync_method: strict
grid_len: #对于outdoor该如何设 for scene01
  coarse: 8 # 20
  middle: 1.28 # 2.64
  fine: 0.64 #1.32
  color: 0.64
  bound_divisable: 0.32
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False #? 分开优化旋转 平移 好像 True False
  const_speed_assumption: True
  gt_camera: False #? True False
  lr: 0.003 # 0.01     
  pixels: 1000 # 5000
  iters: 50
mapping:
  every_frame: 3 #? mapping的频率 1 10
  vis_freq: 50
  vis_inside_freq: 20
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 20 # 20 10
  pixels: 5000 #被用来优化的图像上的像素数吧
  iters_first: 1500
  iters: 80 #60  

cam:  #NOTE: intrinsic is different per scene in TUM e.g: Scene01
  H: 400 # 480 375
  W: 640 # 640 1242
  fx: 299.420633
  fy: 299.420633
  cx: 327.985214 #318.6
  cy: 201.177768 #255.3
  png_depth_scale: 800. #设置 https://europe.naverlabs.com/research/computer-vision/proxy-virtual-worlds-vkitti-2/
  crop_edge: 20